# Generated by Django 4.0.2 on 2022-04-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_color_alter_category_slug_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='vendo',
        ),
    ]
