# Generated by Django 4.0.2 on 2022-04-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_rename_account_name_vendor_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
