# Generated by Django 4.0.2 on 2022-04-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_remove_vendor_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
    ]
