# Generated by Django 4.0.2 on 2022-04-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_remove_vendor_user_vendor_created_by_vendor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='username',
        ),
    ]
