# Generated by Django 4.0.2 on 2022-04-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_remove_vendor_created_by_remove_vendor_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='user',
            new_name='created_by',
        ),
    ]
