# Generated by Django 4.0.2 on 2022-04-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_remove_vendor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCart',
        ),
    ]
